Repository recurly/recurly-client-java, pull requests merged in 2021-04, with the labels that each got.

#144 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  src/main/java/com/recurly/v3/requests/BillingInfoCreate.java
Labels: v4

#147 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: internal, v4

#148 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: internal, v3

#149 Updating release script to obtain version from pom
  scripts/release
Labels: internal, v3

#150 Updating release script to obtain version from pom
  scripts/release
Labels: internal, v4

#152 Specify javadoc executable path in pom.xml
  pom.xml
Labels: internal, v4

#153 Specify javadoc executable path in pom.xml
  pom.xml
Labels: internal, v3

#151 Generated Latest Changes for v2021-02-25 (Backup Payment Method)
  openapi/api.yaml
  src/main/java/com/recurly/v3/requests/BillingInfoCreate.java
  src/main/java/com/recurly/v3/requests/SubscriptionPurchase.java
  src/main/java/com/recurly/v3/resources/BillingInfo.java
  src/main/java/com/recurly/v3/resources/Transaction.java
Labels: v4

#154 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  src/main/java/com/recurly/v3/requests/SubscriptionAddOnTier.java
  src/main/java/com/recurly/v3/resources/SubscriptionAddOnTier.java
Labels: v4
