Repository recurly/recurly-client-java, pull requests merged in 2022-04, with the labels that each got.

#194 Generated Latest Changes for v2019-10-10
  openapi/api.yaml
  src/main/java/com/recurly/v3/resources/Subscription.java
Labels: v3

#195 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
  src/main/java/com/recurly/v3/Constants.java
  src/main/java/com/recurly/v3/requests/AddOnCreate.java
  src/main/java/com/recurly/v3/resources/AddOn.java
  src/main/java/com/recurly/v3/resources/Subscription.java
  src/main/java/com/recurly/v3/resources/SubscriptionAddOn.java
Labels: v4

#196 Adding actions
  .github/workflows/ci.yml
  .travis.yml
  pom.xml
  src/main/java/com/recurly/v3/BaseClient.java
  src/test/java/com/recurly/v3/BaseClientTest.java
Labels: v4, internal

#197 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
  pom.xml
  src/main/java/com/recurly/v3/BaseClient.java
  src/test/java/com/recurly/v3/BaseClientTest.java
Labels: v3, internal
